### ISSUE TITLE
not passing

### ISSUE THREAD

**Issue by Dionne-Stratton** [oustella/coding-exercises#1]
this does not pass a test like this: Input:

a: [-92, -23, 0, 45, 89, 96, 99, 95, 89, 41, -17, -48]

Output:

true

Expected Output:

false

**Comment by oustella** [comment]
@Dionne-Stratton Thanks for pointing that out! Which problem was this?

**Comment by Dionne-Stratton** [comment]
alternating sort.

**Comment by oustella** [comment]
@Dionne-Stratton For the test case you provided, the alter-arranged array becomes [-92, -48, -23, -17, 0, 41, 45, 89, 89, 95, 96, 99]. So it really depends on how the question treats adjacent equal values. I will make a note in the question that in this case, the array would be considered sorted. That said, if you want it to return False, then you would simply modify the line `a[i] > a[j]` to `a[i] >= a[j]`. Hope this helps!
